language: node_js
sudo: false
node_js:
      - 0.10
notifications:
    irc:
        channels:
            - "chat.freenode.net##zuzakistan"
        use_notice: true
        skip_join: true
        on_success: change
        on_failure: change
